baseURL: "https://gryphon85.github.io"
title: My New Hugo Site

theme: "PaperMod"

params:
    profileMode:
        enabled: true
        #imageUrl: "<image link>" # optional
        #imageTitle: "<title of image as alt>" # optional
        #imageWidth: 120 # custom size
        #imageHeight: 120 # custom size
        #buttons:
        #    - name: Archive
        #    url: "/archive"
        #    - name: Github
        #    url: "https://github.com/"

    socialIcons:
        - name: github
          url: "https://github.com/gryphon85"
        - name: instagram
          url: "https://instagram.com"
